version: 2

common_env: &common_env
  MAVEN_OPTS: -Xmx1024m

job_default: &job_defaults
  docker:
    - image: circleci/openjdk:8-jdk-node-browsers

load_m2: &load_m2
  attach_workspace:
    at: ~/.m2

save_m2: &save_m2
  persist_to_workspace:
    root: ~/.m2
    paths:
      - repository/io/syndesis

jobs:
  build:
    <<: *job_defaults
    environment:
      <<: *common_env

    steps:
      - checkout
      - restore_cache:
          key: atlasmap-e2e-qe-mvn-{{ checksum "pom.xml" }}
      - <<: *load_m2
      - run:
          name: Execute tests
          command: |
            ./mvnw clean test  -DskipBuild=true  -Dcucumber.options="--tags @SmokeTests" -Dselenide.headless=true -Dselenide.browser-size=1920x1080
      - run:
          name: Store Cucumber report
          when: always
          command: |
            mkdir -p ~/cucumber
            cp -f datamapper-e2e/target/surefire-reports/TEST-io.atlasmap.qe.test.atlas.CucumberTest.xml ~/cucumber/ui.cucumber
      - store_artifacts:
          path: ui-tests/target/cucumber
      - <<: *save_m2
      - save_cache:
          key: atlasmap-e2e-qe-mvn-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2


